// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spmb-committee/CommitteeDashboard.tsx": () => import("../components/mockups/spmb-committee/CommitteeDashboard.tsx"),
  "./components/mockups/spmb-committee/CommitteeDashboardVariant.tsx": () => import("../components/mockups/spmb-committee/CommitteeDashboardVariant.tsx")
};
